#!/bin/bash
export DISPLAY=:0
source ~/1bash
source ~/1oc
source ~/Resources
OLDCOIN=$COIN
Set_Power
CHECKTEMP1
TMINER=miner
CHECK_CARD
FAN_ADJUST=$__FAN_ADJUST
Make_Logs_Temp
GPUS=$(nvidia-smi --query-gpu=count --format=csv,noheader,nounits | tail -1)
NVD=nvidia-settings
SMI="sudo nvidia-smi"
gpu=0
sl2=0
if [ $GPUS -ge 7 ]; then
sl=0
fi
if [ $GPUS -le 6 ]; then
sl=12
fi
tc=0
rs=0
tl=120
Load_Sequence1
OVERCLOCKCHECK
3MAIN_CHECKOC
CHECK_MINER
sleep 10
if [ $TMINER == ccminer ]; then
        echo -e "${R}${B}WARNING: ${C}$(date)${N} - Waiting on ccminer to connect before starting . . ." | tee -a $LOG_FILE
sleep 60
fi
while true
do
if [ $WTM_AUTO_SWITCH == "YES" ]; then
source ~/1bash
source ~/Logs/WTM_ccoin
COIN=$CCOIN
else
source ~/1bash
fi
CHECK_MINER
if  [[ -z  $(ps ax | grep -i screen | grep miner) ]]
then
if [ $rs -le 13 ]
then
        echo -e "${R}${B}WARNING: ${C}$(date)${N} - miner not running, waiting to start will give $tl seconds if not restarting" | tee -a $LOG_FILE
sleep 10
tl2=$tl-10
if [ $OLDCOIN != $COIN ]; then
echo -e "${R}${B}WARNING: ${C}$(date)${N} - detected coin change lowering overclocks to prevent crash" | tee -a $LOG_FILE
LOWER_OC2
RESET_OC
OLDCOIN=$COIN
elif [ $AUTOMATIC_OVERCLOCK == "YES" ]; then
echo -e "${R}${B}WARNING: ${C}$(date)${N} - detected possible overclock crash setting overclocks back to known overclocks" | tee -a $LOG_FILE
LOWER_OC
RESET_OC2
fi
let tl=tl2
let rs++
fi


if [ $rs == 8 ]
then
        echo -e "${R}${B}WARNING: ${C}$(date)${N} - miner not running, trying nvOC Repairs" | tee -a  $LOG_FILE
miner_fix2
fi
if [ $rs -ge 12 ]
then
        echo -e "${R}${B}WARNING: ${C}$(date)${N} - miner not running, restarting nvOC rig" | tee -a $ALERT_LOG_FILE
sleep 5
reboot
fi
else
tl=120
rs=0
  gpu=0
if [ $GPUS -ge 7 ]; then
if [ $sl -gt 90 ]
then
	sl=45
RESET_OC
fi
fi
if [ $GPUS -le 6 ]; then
if [ $sl -gt 120 ]
then
	sl=60
RESET_OC
fi
fi
if [ $sl2 == $sl ]; then
OVERCLOCKLOAD
  while [ $gpu -lt $GPUS ]
  do
{ IFS=', ' read CURRENT_TEMP CURRENT_FAN POWERDRAW PWRLIMIT; } < <(nvidia-smi -i $gpu --query-gpu=temperature.gpu,fan.speed,power.draw,power.limit --format=csv,noheader,nounits)
		POWERLIMIT=$PWRLIMIT
		POWERLIMIT=$(echo -n $PWRLIMIT | tail -c -6 | head -c -3 )
    		TEMP_DIFF=$((${TARGET_TEMP[${gpu}]} - $CURRENT_TEMP))
    			NEW_FAN_SPEED=$CURRENT_FAN
    echo -e "${B}GPU $gpu${N}, Target temp: ${B}${TARGET_TEMP[${gpu}]}${N}, Current: ${B}$CURRENT_TEMP${N}, Diff: ${B}$TEMP_DIFF${N}, Fan: ${B}$CURRENT_FAN${N}, Power: ${B}$POWERLIMIT${N}" | tee -a ${LOG_FILE}
    						echo ""

TEMPCHECK_1
	if [ $AUTOMATIC_OVERCLOCK == "YES" ];then
for j in $TI
do
	if [ $TMINER == "ewbf" -o $TMINER == "zm" -o $TMINER == "ccminer" ];then
OVERCLOCK001
	fi
	if [ $TMINER == "miner" ];then
OVERCLOCK002
	fi
	  done
	fi
    let gpu++
	done
let sl++
sl2=0
 echo -e "${B}-------------------------------------------------------------------------------------------------------------------------------------"
TEMPCHECK_2
else
sleep 1
fi
let sl2++
fi
done



