#!/bin/bash
########## DONT TOUCH BELOW THIS LINE ############
source ~/1bash
source ~/Resources
3Main_Coin_Sequence(){
CHECK_CARD
CHECK_I
miner_fix2
if [ $WTM_AUTO_SWITCH == "YES" ]; then
source ~/Logs/WTM_ccoin
COIN=$CCOIN
fi
########## DONT TOUCH ABOVE THIS LINE ############
########## ADD COINS BELOW THIS LINE #############
if [ $COIN == "NICEHASH_NEOSCRYPT" ]
then
 HCD='/home/m1/Miners/KTccminer/ccminer'
 ADDR="$NICEHASH_BTC_ADDRESS.$NICEHASH_WORKER"
 screen -dmSL miner $HCD -a neoscrypt -o stratum+tcp://$NICEHASH_NEOSCRYPT_POOL:$NICEHASH_NEOSCRYPT_PORT -u $ADDR -p x -i $NICEHASH_NEOSCRYPT_INTENSITY
fi

if [ $COIN == "NICEHASH_LYRA2REV2" ]
then
 HCD='/home/m1/Miners/alccminer/ccminer' miner_start1 
 ADDR="$NICEHASH_BTC_ADDRESS.$NICEHASH_WORKER"
 screen -dmSL miner $HCD -a lyra2v2 -o stratum+tcp://$NICEHASH_LYRA2REV2_POOL:$NICEHASH_LYRA2REV2_PORT -u $ADDR -p x -i $NICEHASH_LYRA2REV2_INTENSITY 
fi

if [ $COIN == "NICEHASH_X11GOST" ]
then
 HCD='/home/m1/Miners/SPccminer/ccminer' 
 ADDR="$$NICEHASH_BTC_ADDRESS.$NICEHASH_WORKER" 
 screen -dmSL miner $HCD -a sib -o stratum+tcp://$NICEHASH_X11GOST_POOL:$NICEHASH_X11GOST_PORT -u $ADDR -p x -i $NICEHASH_X11GOST_INTENSITY 
fi

if [ $COIN == "NICEHASH_SKUNKHASH" ]
then
 HCD='/home/m1/Miners/TPccminer/ccminer'
 ADDR="$NICEHASH_BTC_ADDRESS.$NICEHASH_WORKER"
 screen -dmSL miner $HCD -a skunk -o stratum+tcp://$NICEHASH_SKUNKHASH_POOL:$NICEHASH_SKUNKHASH_PORT -u $ADDR -p x -i $NICEHASH_SKUNKHASH_INTENSITY 
fi

if [ $COIN == "NICEHASH_CRYPTONIGHT" ] 
then
 HCD='/home/m1/Miners/KTccminer-cryptonight/ccminer'
 ADDR="$NICEHASH_BTC_ADDRESS.$NICEHASH_WORKER"
 screen -dmSL miner $HCD -o stratum+tcp://$NICEHASH_CRYPTONIGHT_POOL:$NICEHASH_CRYPTONIGHT_PORT -u $ADDR -p x -i $NICEHASH_CRYPTONIGHT_INTENSITY 
fi

if [ $COIN == "NICE_ETHASH" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

NICEADDR="$BTC_ADDRESS.$NICE_ETHASH_WORKER"

screen -dmSL miner $HCD -SP 2 -S $GENOIL_NICE_ETHASH_POOL -O $NICEADDR:x -U
fi
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

NICEADDR="$BTC_ADDRESS.$NICE_ETHASH_WORKER"

screen -dmSL miner $HCD -SP 2 -S $GENOIL_NICE_ETHASH_POOL -O $NICEADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

NICEADDR="$BTC_ADDRESS.$NICE_ETHASH_WORKER"

screen -dmSL miner $HCD -epool $NICE_ETHASH_POOL -ewal $NICEADDR -epsw x -esm 3 -allpools 1 -estale 0 -dbg -1 $NICE_ETHASH_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "ONION" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
ADDR="$ONION_ADDRESS"

screen -dmSL miner $HCD -a x13 -o $ONION_POOL -u $ADDR -p c=ONION -i $OCIT
fi

if [ $COIN == "SMART" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
ADDR="$SMART_ADDRESS.$SMART_WORKER"
screen -dmSL miner $HCD -a keccak -o $SMART_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "MNX" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

MNXADDR="$MNX_ADDRESS.$MNX_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $MNX_POOL --user $MNXADDR --pass $MINER_PWD --port $MNX_PORT  --time $ZM_OPTS ;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
    screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $MNX_POOL --user $MNXADDR --pass $MINER_PWD --port $MNX_PORT  $EWBF_OPTS ;
fi
fi
if [ $COIN == "BTG" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

BTGADDR="$BTG_ADDRESS.$BTG_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $BTG_POOL --user $BTGADDR --pass $MINER_PWD --port $BTG_PORT  --time $ZM_OPTS ;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $BTG_POOL --user $BTGADDR --pass $MINER_PWD --port $BTG_PORT  $EWBF_OPTS ;
fi
fi
if [ $COIN == "ZEC" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

ZECADDR="$ZEC_ADDRESS.$ZEC_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
    screen -dmSL miner $HCD --server $ZEC_POOL --user $ZECADDR --pass $MINER_PWD --port $ZEC_PORT  --time $ZM_OPTS ;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
 screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $ZEC_POOL --user $ZECADDR --pass $MINER_PWD --port $ZEC_PORT  $EWBF_OPTS ;
fi
fi

if [ $COIN == "ZCL" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

ZCLADDR="$ZCL_ADDRESS.$ZCL_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
    screen -dmSL miner $HCD --server $ZCL_POOL --user $ZCLADDR --pass $MINER_PWD --port $ZCL_PORT  --time $ZM_OPTS ;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
    screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $ZCL_POOL --user $ZCLADDR --pass $MINER_PWD --port $ZCL_PORT  $EWBF_OPTS ;
fi
fi

if [ $COIN == "NICE_EQUIHASH" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

NICE_EQUIHASHADDR="$NICE_EQUIHASH_ADDRESS.$NICE_EQUIHASH_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $NICE_EQUIHASH_POOL --user $NICE_EQUIHASHADDR --pass $MINER_PWD --port $NICE_EQUIHASH_PORT;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $NICE_EQUIHASH_POOL --user $NICE_EQUIHASHADDR --pass $MINER_PWD --port $NICE_EQUIHASH_PORT;
fi
fi

if [ $COIN == "BTCZ" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi
BTCZADDR="$BTCZ_ADDRESS.$BTCZ_WORKER"
if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
    screen -dmSL miner $HCD --server $BTCZ_POOL --user $BTCZADDR --pass $MINER_PWD --port $BTCZ_PORT  --time $ZM_OPTS ;
fi
if [ $ZM_or_EWBF == "EWBF" ]
then
    screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $BTCZ_POOL --user $BTCZADDR --pass $MINER_PWD --port $BTCZ_PORT  $EWBF_OPTS ;
fi
fi

if [ $COIN == "KMD" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

KMDADDR="$KMD_ADDRESS.$KMD_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $KMD_POOL --user $KMDADDR --pass $MINER_PWD --port $KMD_PORT --time $ZM_OPTS;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $KMD_POOL --user $KMDADDR --pass $MINER_PWD --port $KMD_PORT $EWBF_OPTS;
fi
fi

if [ $COIN == "ZEN" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

ZENADDR="$ZEN_ADDRESS.$ZEN_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $ZEN_POOL --user $ZENADDR --pass $MINER_PWD --port $ZEN_PORT --time $ZM_OPTS;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $ZEN_POOL --user $ZENADDR --pass $MINER_PWD --port $ZEN_PORT $EWBF_OPTS;
fi
fi

if [ $COIN == "HUSH" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

HUSHADDR="$HUSH_ADDRESS.$HUSH_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $HUSH_POOL --user $HUSHADDR --pass $MINER_PWD --port $HUSH_PORT --time $ZM_OPTS;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $HUSH_POOL --user $HUSHADDR --pass $MINER_PWD --port $HUSH_PORT $EWBF_OPTS;
fi
fi

if [ $COIN == "MPH_EQUIHASH" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

MPHADDR="$MPH_USERNAME.$MPH_WORKER"

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $MPH_EQUIHASH_POOL --user $MPHADDR --pass $MINER_PWD --port $MPH_EQUIHASH_PORT --time $ZM_OPTS;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $MPH_EQUIHASH_POOL --user $MPHADDR --pass $MINER_PWD --port $MPH_EQUIHASH_PORT $EWBF_OPTS;
fi
fi

if [ $COIN == "ZPOOL_EQUIHASH" ]
then
if [ $EWBF_VERSION == "3_4" ]
then
HCD='/home/m1/Miners/zec/v3_4/ewbf'
fi

if [ $ZM_or_EWBF == "ZM" ]
then
HCD='/home/m1/Miners/zec/zm/5_8/zm'
screen -dmSL miner $HCD --server $ZPOOL_EQUIHASH_POOL --user $BTC_ADDRESS --pass $ZPOOLPASS --port $ZPOOL_EQUIHASH_PORT --time $ZM_OPTS;
fi

if [ $ZM_or_EWBF == "EWBF" ]
then
screen -dmSL miner $HCD --eexit 3 --fee $EWBF_PERCENT --pec --server $ZPOOL_EQUIHASH_POOL --user $BTC_ADDRESS --pass $ZPOOLPASS --port $ZPOOL_EQUIHASH_PORT $EWBF_OPTS;
fi
fi

if [ $COIN == "ZCOIN" ]
then
#HCD='/home/m1/Miners/alccminer/ccminer'
HCD='/home/m1/Miners/ccminer223/ccminer'
ADDR="$ZCOIN_ADDRESS.$ZCOIN_WORKER"
miner_start1
#screen -dmSL miner $HCD -a lyra2z -o $ZCOIN_POOL -u $ADDR -p $MINER_PWD -i $OCIT
screen -dmSL miner $HCD -a lyra2z --cpu-priority 0 -o $ZCOIN_POOL -u $ADDR -p $MINER_PWD
fi

if [ $COIN == "BTX" ]
then
HCD='/home/m1/Miners/ccminer223/ccminer'
ADDR="$BTX_ADDRESS.$BTX_WORKER"
miner_start1
screen -dmSL miner $HCD -a timetravel10 -o $BTX_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "ZPOOL_lyra2v2 --cpu-priority 0" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'

screen -dmSL miner $HCD -a lyra2v2 --cpu-priority 0 -o $ZPOOL_lyra2v2 --cpu-priority 0_POOL -u $BTC_ADDRESS -p $ZPOOLPASS -i $ZPOOL_lyra2v2 --cpu-priority 0 -i $OCIT
fi

if [ $COIN == "ZPOOL_LBRY" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'

screen -dmSL miner $HCD -a lbry -o $ZPOOL_LBRY_POOL -u $BTC_ADDRESS -p $ZPOOLPASS -i $OCIT
fi

if [ $COIN == "ZPOOL_NEOSCRYPT" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'

screen -dmSL miner $HCD -a neoscrypt -o $ZPOOL_NEOSCRYPT_POOL -u $BTC_ADDRESS -p $ZPOOLPASS -i $OCIT
fi

if [ $COIN == "ZPOOL_SKEIN" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'

screen -dmSL miner $HCD -a skein -o $ZPOOL_SKEIN_POOL -u $BTC_ADDRESS -p $ZPOOLPASS -i $OCIT
fi

if [ $COIN == "ZPOOL_BLAKE2S" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'

screen -dmSL miner $HCD -a blake2s -o $ZPOOL_BLAKE2S_POOL -u $BTC_ADDRESS -p $ZPOOLPASS -i $OCIT
fi

if [ $COIN == "MONA" ]
then
HCD='/home/m1/Miners/ccminer223/ccminer'
ADDR="$MONA_ADDRESS.$MONA_WORKER"
miner_start1
screen -dmSL miner $HCD -a lyra2v2 --cpu-priority 0 -o stratum+tcp://$MONA_POOL:$MONA_PORT -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "XVG_X17" ]
then
HCD='/home/m1/Miners/alccminer/ccminer'
ADDR="$XVG_ADDRESS.$XVG_WORKER"
PASSWORD="$XVG_PASSWORD"
miner_start1
screen -dmSL miner $HCD -a x17 --cpu-priority 0 -o $XVG_POOL -u $ADDR -p $PASSWORD
fi

if [ $COIN == "XLR" ]
then
HCD='/home/m1/Miners/ccminer-xevan/ccminer'
ADDR="$XLR_ADDRESS.$XLR_WORKER"
PASSWORD="$XLR_PASSWORD"
miner_start1
screen -dmSL miner $HCD -a xevan --cpu-priority 0 -o $XLR_POOL -u $ADDR -p $PASSWORD
fi

if [ $COIN == "CRC" ]
then
HCD='/home/m1/Miners/ccminer223/ccminer'
ADDR="$CRC_ADDRESS.$CRC_WORKER"
PASSWORD="$CRC_PASSWORD"
miner_start1
screen -dmSL miner $HCD -a neoscrypt --cpu-priority 0 -o $CRC_POOL -u $ADDR -p $PASSWORD
fi


if [ $COIN == "DMD" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
ADDR="$DMD_ADDRESS.$DMD_WORKER"

screen -dmSL miner $HCD -a dmd-gr -o $DMD_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "GRS" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
ADDR="$GRS_ADDRESS.$GRS_WORKER"

screen -dmSL miner $HCD -a groestl -o $GRS_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "XMY" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
ADDR="$XMY_ADDRESS.$XMY_WORKER"

screen -dmSL miner $HCD -a myr-gr -o $XMY_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "VTC" ]
then
HCD='/home/m1/Miners/vertminer/ccminer'
ADDR="$VTC_ADDRESS.$VTC_WORKER"

if [ $VTC_AUTOCONVERT_TO_BTC == "YES" ]
then
ADDR="$BTC_ADDRESS.$VTC_WORKER"


screen -dmSL miner $HCD -a lyra2v2 --cpu-priority 0 -o $VTC_POOL -u $ADDR -p c=BTC -i $OCIT
fi

if [ $VTC_AUTOCONVERT_TO_BTC == "NO" ]
then


screen -dmSL miner $HCD -a lyra2v2 --cpu-priority 0 -o $VTC_POOL -u $ADDR -p c=VTC -i $OCIT
fi
fi

if [ $COIN == "DGB" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
ADDR="$DGB_ADDRESS"

if [ $DGB_AUTOCONVERT_TO_BTC == "YES" ]
then
ADDR="$BTC_ADDRESS"

screen -dmSL miner $HCD -a skein -o $DGB_POOL -u $ADDR -p c=BTC -i $OCIT
fi

if [ $DGB_AUTOCONVERT_TO_BTC == "NO" ]
then

screen -dmSL miner $HCD -a skein -o $DGB_POOL -u $ADDR -p c=DGB -i $OCIT
fi
fi

if [ $COIN == "ZPOOL_SKUNK" ]
then
HCD='/home/m1/Miners/KXccminer-skunk/ccminer'
ADDR="$SKUNK_ADDRESS.$SKUNK_WORKER"

if [ $SKUNK_AUTOCONVERT_TO_BTC == "YES" ]
then
ADDR="$BTC_ADDRESS.$SKUNK_WORKER"

screen -dmSL miner $HCD -a skunk -o $SKUNK_POOL -u $ADDR -p $ZPOOLPASS -i $OCIT
fi

if [ $SKUNK_AUTOCONVERT_TO_BTC == "NO" ]
then

screen -dmSL miner $HCD -a skunk -o $SKUNK_POOL -u $ADDR -p c=SIGT -i $OCIT
fi
fi

if [ $COIN == "LBC" ]
then
HCD='/home/m1/Miners/alccminer/ccminer'
ADDR="$LBC_ADDRESS.$LBC_WORKER"
miner_start1
screen -dmSL miner $HCD -a lbry -o $LBC_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "FTC" ]
then
HCD='/home/m1/Miners/ccminer223/ccminer'
ADDR="$FTC_ADDRESS.$FTC_WORKER"
miner_start1
screen -dmSL miner $HCD -a neoscrypt -o $FTC_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "LUX_PHI1612" ]
then
HCD='/home/m1/Miners/ccminer223/ccminer'
ADDR="$LUX_ADDRESS.$LUX_WORKER"
miner_start1
screen -dmSL miner $HCD -a phi --cpu-priority 0 -o $LUX_POOL -u $ADDR -p $LUX_PWD -i $OCIT
fi

if [ $COIN == "KRB" ]
then
HCD='/home/m1/Miners/KTccminer-cryptonight/ccminer'
ADDR="$KRB_ADDRESS.$KRB_WORKER"

screen -dmSL miner $HCD -o $KRB_POOL -u $ADDR -p $MINER_PWD
fi

if [ $COIN == "ETN" ]
then
HCD='/home/m1/Miners/TPccminer/ccminer'
ADDR="$ETN_ADDRESS.$ETN_WORKER"

screen -dmSL miner $HCD -o $ETN_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "ORB" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
ADDR="$ORB_ADDRESS.$ORB_WORKER"

screen -dmSL miner $HCD -a neoscrypt -o $ORB_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "TZC" ]
then
HCD='/home/m1/Miners/ccminer223/ccminer'
ADDR="$TZC_ADDRESS"
miner_start1
screen -dmSL miner $HCD -a neoscrypt -o $TZC_POOL -u $ADDR -p $TZC_PWD -i $OCIT
fi

if [ $COIN == "VIVO" ]
then
HCD='/home/m1/Miners/SPccminer/ccminer'
ADDR="$VIVO_ADDRESS.$VIVO_WORKER"

screen -dmSL miner $HCD -a neoscrypt -o $VIVO_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "PXC" ]
then
HCD='/home/m1/Miners/KXccminer-skunk/ccminer'
ADDR="$PXC_ADDRESS/$PXC_WORKER"

screen -dmSLL miner $HCD -a neoscrypt -o $PXC_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "SIB" ]
then
HCD='/home/m1/Miners/SPccminer/ccminer'
ADDR="$SIB_ADDRESS.$SIB_WORKER"

screen -dmSLL miner $HCD -a sib -o $SIB_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "SKUNK" ]
then
HCD='/home/m1/Miners/KXccminer-skunk/ccminer'
ADDR="$SKUNK_ADDRESS.$SKUNK_WORKER"

screen -dmSL miner $HCD -a skunk -o $SKUNK_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "ALTCOM" ]
then
HCD='/home/m1/Miners/KXccminer-skunk/ccminer'
ADDR="$ALTCOM_ADDRESS.$ALTCOM_WORKER"

screen -dmSL miner $HCD -a skunk -o $ALTCOM_POOL -u $ADDR -p $MINER_PWD -i $OCIT
fi
if [ $COIN == "XMR" ]
then
HCD='/home/m1/Miners/xmr/stakGPU/bin/xmr-stak-nvidia'
ADDR="$XMR_ADDRESS.$XMR_WORKER"

GPUS_FOR_XMR=0
echo "" > /home/m1/Miners/tmp_threads

while [ $GPUS_FOR_XMR != $GPUS ]
do

cat <<EOF >>/home/m1/Miners/tmp_threads
{ "index" : $GPUS_FOR_XMR,
    "threads" : 32, "blocks" : 18,
    "bfactor" : 8, "bsleep" :  10,
    "affine_to_cpu" : false,
  },
EOF
GPUS_FOR_XMR=$(($GPUS_FOR_XMR+1))
done

THREADS=$(cat /home/m1/Miners/tmp_threads)

cat <<EOF >/home/m1/Miners/xmr/stakGPU/bin/config.txt

"gpu_threads_conf" : [
$THREADS
],

"use_tls" : false,
"tls_secure_algo" : true,
"tls_fingerprint" : "",

"pool_address" : "$XMR_POOL",
"wallet_address" : "$ADDR",
"pool_password" : "x",

"call_timeout" : 10,
"retry_time" : 10,
"giveup_limit" : 0,

"verbose_level" : 4,

"h_print_time" : 60,

"output_file" : "",

"httpd_port" : 0,

"prefer_ipv4" : true
EOF

cd /home/m1/Miners/xmr/stakGPU/bin

screen -dmSL miner $HCD

rm /home/m1/Miners/tmp_threads
fi

if [ $COIN == "PIRL" ]
then
 
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'
 
PIRLADDR="$PIRL_ADDRESS/$PIRL_WORKER"
 
if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
PIRLADDR="$PIRL_ADDRESS.$PIRL_WORKER"
fi
 
screen -dmSL miner $HCD -S $PIRL_POOL -O $PIRLADDR:x -SP 1 -U
fi
 
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'
 
PIRLADDR="$PIRL_ADDRESS/$PIRL_WORKER"
 
if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
PIRLADDR="$PIRL_ADDRESS.$PIRL_WORKER"
fi
 
screen -dmSL miner $HCD -S $PIRL_POOL -O $PIRLADDR:x -SP 1 -U
fi
 
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then
 
HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64
 
PIRLADDR="$PIRL_ADDRESS/$PIRL_WORKER"
 
if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
PIRLADDR="$PIRL_ADDRESS.$PIRL_WORKER"
fi
 
screen -dmSL miner $HCD -epool $PIRL_POOL -ewal $PIRLADDR -epsw x -mode 1 -allpools 1 -dbg -1 $PIRL_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "UBQ" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

screen -dmSL miner $HCD -S $UBQ_POOL -O $UBQADDR:x -SP 1 -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

screen -dmSL miner $HCD -S $UBQ_POOL -O $UBQADDR:x -SP 1 -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

screen -dmSL miner $HCD -epool $UBQ_POOL -ewal $UBQADDR -epsw x -mode 1 -allpools 1 -dbg -1 $UBQ_EXTENSION_ARGUMENTS
fi
fi
if [ $COIN == "ETC" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

screen -dmSL miner $HCD -S $ETC_POOL -O $ETCADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

screen -dmSL miner $HCD -S $ETC_POOL -O $ETCADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

screen -dmSL miner $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -mode 1 -dbg -1 $ETC_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "EXP" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

EXPADDR="$EXP_ADDRESS.$EXP_WORKER"

screen -dmSL miner $HCD -S $EXP_POOL -O $EXPADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
EXPADDR="$EXP_ADDRESS.$EXP_WORKER"
fi

screen -dmSL miner $HCD -S $EXP_POOL -O $EXPADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"

screen -dmSL miner $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -mode 1 -allpools 1 -dbg -1 $EXP_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "ETH" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

screen -dmSL miner $HCD -S $ETH_POOL -O $ETHADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

screen -dmSL miner $HCD -S $ETH_POOL -O $ETHADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

screen -dmSL miner $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -mode 1 -dbg -1 $ETH_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "MPH_ETHASH" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

MPH_ETHASH_ADDR="$MPH_ADDRESS/$MPH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
MPH_ETHASH_ADDR="$MPH_ADDRESS.$MPH_WORKER"
fi

screen -dmSL miner $HCD -S $MPH_ETHASH_POOL -O $MPH_ETHASH_ADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

MPH_ETHASH_ADDR="$MPH_ADDRESS/$MPH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
MPH_ETHASH_ADDR="$MPH_ADDRESS.$MPH_WORKER"
fi

screen -dmSL miner $HCD -S $MPH_ETHASH_POOL -O $MPH_ETHASH_ADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

MPH_ETHASH_ADDR="$MPH_ADDRESS/$MPH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
MPH_ETHASH_ADDR="$MPH_ADDRESS.$MPH_WORKER"
fi

screen -dmSL miner $HCD -epool $MPH_ETHASH_POOL -ewal $MPH_ETHASH_ADDR -epsw x -mode 1 -dbg -1 $MPH_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "MUSIC" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

MUSICADDR="$MUSIC_ADDRESS.$MUSIC_WORKER"

screen -dmSL miner $HCD -S $MUSIC_POOL -O $MUSICADDR:x -U
fi
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
MUSICADDR="$MUSIC_ADDRESS.$MUSIC_WORKER"
fi

screen -dmSL miner $HCD -S $MUSIC_POOL -O $MUSICADDR:x -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"

screen -dmSL miner $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -mode 1 -allpools 1 -dbg -1 $MUSIC_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "SOIL" ]
then
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "GENOIL" ]
then
HCD='/home/m1/Miners/eth/Genoil-U/ethminer'

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

screen -dmSL miner $HCD -S $SOIL_POOL -O $SOILADDR:x -SP 1 -U
fi
if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "ETHMINER" ]
then
HCD='/home/m1/Miners/eth/ethminer_12dev2/ethminer'

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
SOILADDR="$SOIL_ADDRESS.$SOIL_WORKER"
fi

screen -dmSL miner $HCD -S $SOIL_POOL -O $SOILADDR:x -SP 1 -U
fi

if [ $ETHMINER_or_GENOIL_or_CLAYMORE == "CLAYMORE" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

screen -dmSL miner $HCD -epool $SOIL_POOL -ewal $SOILADDR -epsw x -mode 1 -allpools 1 -dbg -1 $SOIL_EXTENSION_ARGUMENTS
fi
fi

if [ $COIN == "DCR" ]
then
HCD='/home/m1/Miners/pasc/sgminer'
ADDR="$DCR_ADDRESS.$DCR_WORKER"

screen -dmSL miner $HCD -k decred -o $DCR_POOL -u $ADDR -p $MINER_PWD -p $MINER_PWD -I 21 -w 64 -g2
fi

if [ $COIN == "PASC" ]
then
HCD='/home/m1/Miners/pasc/sgminer'
ADDR="$PASC_ADDRESS..$PASC_WORKER"

screen -dmSL miner $HCD -k pascal -o $PASC_POOL -u $ADDR -p $MINER_PWD -p $MINER_PWD -I 21 -w 64 -g2
fi

if [ $COIN == "PASL" ]
then
HCD='/home/m1/Miners/pasc/sgminer'
ADDR="$PASL_ADDRESS..$PASL_WORKER"

screen -dmSL miner $HCD -k pascal -o $PASL_POOL -u $ADDR -p $MINER_PWD -p $MINER_PWD -I 21 -w 64 -g2
fi

if [ $COIN == "SIA" ]
then
HCD='/home/m1/Miners/ccminer/ccminer'
SCADDR="$SC_ADDRESS/$SC_WORKER"

screen -dmSL miner $HCD -a sia -o $SC_GW_POOL -u $SCADDR -p $MINER_PWD -i $OCIT
fi

if [ $COIN == "DUAL_NICEHASH" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETHASH_ADDR="$DUAL_BTC_ADDRESS.$DUAL_WORKER"
DCR_ADDR="$DUAL_BTC_ADDRESS.$DUAL_WORKER"

screen -dmSL miner $HCD -epool $DUAL_ETHASH_POOL -ewal $ETHASH_ADDR -epsw x -allcoins 1 -allpools 1 -dpool $DUAL_DCR_POOL -dwal $DCR_ADDR -dpsw x $DUAL_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETC_DCR" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

DADDR="$DCR_ADDRESS.$DCR_WORKER"

screen -dmSL miner $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $DCR_POOL -dwal $DADDR -dpsw x -dcoin dcr -allcoins 1 -allpools 1 -dbg -1 $ETC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETC_PASC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

ADDR="$PASC_ADDRESS..$PASC_WORKER"

screen -dmSL miner $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $ETC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETC_PASL" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

ADDR="$PASL_ADDRESS..$PASL_WORKER"

screen -dmSL miner $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $PASL_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $ETC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETC_LBC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

ADDR="$LBC_ADDRESS.$LBC_WORKER"

screen -dmSL miner $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -allcoins 1 -allpools 1 -dbg -1 $ETC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETC_SC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETCADDR="$ETC_ADDRESS/$ETC_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETCADDR="$ETC_ADDRESS.$ETC_WORKER"
fi

SCADDR="$SC_ADDRESS/$SC_WORKER"

screen -dmSL miner $HCD -epool $ETC_POOL -ewal $ETCADDR -epsw x -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -allcoins 1 -allpools 1 -dbg -1 $ETC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_EXP_DCR" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
DADDR="$DCR_ADDRESS.$DCR_WORKER"

screen -dmSL miner $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -dpool $DCR_POOL -dwal $DADDR -dcoin drc -allcoins 1 -allpools 1 -dpsw x $EXP_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_EXP_PASC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

EXPADDR="$EXP_ADDRESS.$EXP_WORKER"
ADDR="$PASC_ADDRESS..$PASC_WORKER"

screen -dmSL miner $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $EXP_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_EXP_PASL" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

EXPADDR="$EXP_ADDRESS.$EXP_WORKER"
ADDR="$PASL_ADDRESS..$PASL_WORKER"

screen -dmSL miner $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -dpool $PASL_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $EXP_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_EXP_LBC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
ADDR="$LBC_ADDRESS.$LBC_WORKER"

screen -dmSL miner $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -allcoins 1 -allpools 1 -dbg -1 $EXP_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_EXP_SC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

EXPADDR="$EXP_ADDRESS/$EXP_WORKER"
SCADDR="$SC_ADDRESS/$SC_WORKER"

screen -dmSL miner $HCD -epool $EXP_POOL -ewal $EXPADDR -epsw x -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -allcoins 1 -allpools 1 -dbg -1 $EXP_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_MUSIC_DCR" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
DADDR="$DCR_ADDRESS.$DCR_WORKER"

screen -dmSL miner $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -dpool $DCR_POOL -dwal $DADDR -dpsw x -dcoin dcr -allcoins 1 -allpools 1 -dbg -1 $MUSIC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_MUSIC_PASC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
ADDR="$PASC_ADDRESS..$PASC_WORKER"

screen -dmSL miner $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $MUSIC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_MUSIC_PASL" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
ADDR="$PASL_ADDRESS..$PASL_WORKER"

screen -dmSL miner $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -dpool $PASL_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $MUSIC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_MUSIC_LBC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
ADDR="$LBC_ADDRESS.$LBC_WORKER"

screen -dmSL miner $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -allcoins 1 -allpools 1 -dbg -1 $MUSIC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_MUSIC_SC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

MUSICADDR="$MUSIC_ADDRESS/$MUSIC_WORKER"
SCADDR="$SC_ADDRESS/$SC_WORKER"

screen -dmSL miner $HCD -epool $MUSIC_POOL -ewal $MUSICADDR -epsw x -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -allcoins 1 -allpools 1 -dbg -1 $MUSIC_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETH_DCR" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

DADDR="$DCR_ADDRESS.$DCR_WORKER"

screen -dmSL miner $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $DCR_POOL -dwal $DADDR -dpsw x -dcoin dcr -allcoins 1 -allpools 1 -dbg -1 $ETH_EXTENSION_ARGUMENTS

fi

if [ $COIN == "DUAL_ETH_PASC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

ADDR="$PASC_ADDRESS..$PASC_WORKER"

screen -dmSL miner $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $ETH_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETH_PASL" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

ADDR="$PASL_ADDRESS..$PASL_WORKER"

screen -dmSL miner $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $PASL_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $ETH_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETH_LBC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

ADDR="$LBC_ADDRESS.$LBC_WORKER"

screen -dmSL miner $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -allcoins 1 -allpools 1 -dbg -1 $ETH_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_ETH_SC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

ETHADDR="$ETH_ADDRESS/$ETH_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
ETHADDR="$ETH_ADDRESS.$ETH_WORKER"
fi

SCADDR="$SC_ADDRESS/$SC_WORKER"

screen -dmSL miner $HCD -epool $ETH_POOL -ewal $ETHADDR -epsw x -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -allcoins 1 -allpools 1 -dbg -1 $ETH_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_SOIL_DCR" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
SOILADDR="$SOIL_ADDRESS.$SOIL_WORKER"
fi

DADDR="$DCR_ADDRESS.$DCR_WORKER"

screen -dmSL miner $HCD -epool $SOIL_POOL -ewal $SOIL_ADDRESS -eworker $SOIL_WORKER -epsw x -dpool $DCR_POOL -dwal $DADDR -dpsw x -dcoin dcr -allcoins 1 -allpools 1 -dbg -1 $SOIL_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_SOIL_PASC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
SOILADDR="$SOIL_ADDRESS.$SOIL_WORKER"
fi

ADDR="$PASC_ADDRESS..$PASC_WORKER"

screen -dmSL miner $HCD -epool $SOIL_POOL -ewal $SOIL_ADDRESS -eworker $SOIL_WORKER -epsw x -dpool $PASC_POOL -dwal $ADDR -dcoin pasc -allcoins 1 -allpools 1 -dpsw x $SOIL_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_SOIL_PASL" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
SOILADDR="$SOIL_ADDRESS.$SOIL_WORKER"
fi

ADDR="$PASL_ADDRESS..$PASL_WORKER"

screen -dmSL miner $HCD -epool $SOIL_POOL -ewal $SOIL_ADDRESS -eworker $SOIL_WORKER -epsw x -dpool $PASL_POOL -dwal $ADDR -dcoin pasc -allcoins 1 -allpools 1 -dpsw x $SOIL_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_SOIL_LBC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
SOILADDR="$SOIL_ADDRESS.$SOIL_WORKER"
fi

ADDR="$LBC_ADDRESS.$LBC_WORKER"

screen -dmSL miner $HCD -epool $SOIL_POOL -ewal $SOIL_ADDRESS -eworker $SOIL_WORKER -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -allcoins 1 -allpools 1 -dpsw x $SOIL_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_SOIL_SC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

SOILADDR="$SOIL_ADDRESS/$SOIL_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
SOILADDR="$SOIL_ADDRESS.$SOIL_WORKER"
fi

SCADDR="$SC_ADDRESS/$SC_WORKER"

screen -dmSL miner $HCD -epool $SOIL_POOL -ewal $SOIL_ADDRESS -eworker $SOIL_WORKER -epsw x -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -allcoins 1 -allpools 1 -dpsw x $SOIL_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_UBQ_DCR" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

DADDR="$DCR_ADDRESS.$DCR_WORKER"

screen -dmSL miner $HCD -epool $UBQ_POOL -ewal $UBQ_ADDRESS -eworker $UBQ_WORKER -epsw x -dpool $DCR_POOL -dwal $DADDR -dpsw x -dcoin dcr -allcoins 1 -allpools 1 -dbg -1 $UBQ_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_UBQ_PASC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

ADDR="$PASC_ADDRESS..$PASC_WORKER"

screen -dmSL miner $HCD -epool $UBQ_POOL -ewal $UBQ_ADDRESS -eworker $UBQ_WORKER -epsw x -dpool $PASC_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $UBQ_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_UBQ_PASL" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

ADDR="$PASL_ADDRESS..$PASL_WORKER"

screen -dmSL miner $HCD -epool $UBQ_POOL -ewal $UBQ_ADDRESS -eworker $UBQ_WORKER -epsw x -dpool $PASL_POOL -dwal $ADDR -dpsw x -dcoin pasc -allcoins 1 -allpools 1 -dbg -1 $UBQ_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_UBQ_LBC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64

UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

ADDR="$LBC_ADDRESS.$LBC_WORKER"

screen -dmSL miner $HCD -epool $UBQ_POOL -ewal $UBQ_ADDRESS -eworker $UBQ_WORKER -epsw x -dpool $LBC_POOL -dwal $ADDR -dpsw x -dcoin lbc -allcoins 1 -allpools 1 -dbg -1 $UBQ_EXTENSION_ARGUMENTS
fi

if [ $COIN == "DUAL_UBQ_SC" ]
then

HCD=/home/m1/Miners/eth/$CLAYMORE_VERSION/ethdcrminer64


UBQADDR="$UBQ_ADDRESS/$UBQ_WORKER"

if [ $DOT_POOL_FORMAT_or_FORWARD_SLASH_POOL_FORMAT == "DOT" ]
then
UBQADDR="$UBQ_ADDRESS.$UBQ_WORKER"
fi

SCADDR="$SC_ADDRESS/$SC_WORKER"

screen -dmSL miner $HCD -epool $UBQ_POOL -ewal $UBQ_ADDRESS -eworker $UBQ_WORKER -epsw x -dpool $SC_POOL -dwal $SCADDR -dpsw x -dcoin sc -allcoins 1 -allpools 1 -dbg -1 $UBQ_EXTENSION_ARGUMENTS
fi
}
