#!/bin/bash

source ~/8coinsv2
#----  fill in your coins and uncomment the lines concerned  ----
#365
#365_WORKER=$WORKERNAME
#365_ADDRESS="replace_with_your_ZCL_address"
#365_POOL="replace_with_your_pool_and_port"
#365_POOL="replace_with_your_pool_and_port"
#365_PASSWORD="x"
#365
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ADN
#ADN_WORKER=$WORKERNAME
#ADN_ADDRESS="replace_with_your_ZCL_address"
#ADN_POOL="replace_with_your_pool_and_port"
#ADN_POOL="replace_with_your_pool_and_port"
#ADN_PASSWORD="x"
#ADN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ADZ
#ADZ_WORKER=$WORKERNAME
#ADZ_ADDRESS="replace_with_your_ZCL_address"
#ADZ_POOL="replace_with_your_pool_and_port"
#ADZ_POOL="replace_with_your_pool_and_port"
#ADZ_PASSWORD="x"
#ADZ
# 
#----  fill in your coins and uncomment the lines concerned  ----
#AEON
#AEON_WORKER=$WORKERNAME
#AEON_ADDRESS="replace_with_your_ZCL_address"
#AEON_POOL="replace_with_your_pool_and_port"
#AEON_POOL="replace_with_your_pool_and_port"
#AEON_PASSWORD="x"
#AEON
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ALTCOM
#ALTCOM_WORKER=$WORKERNAME
#ALTCOM_ADDRESS="replace_with_your_ZCL_address"
#ALTCOM_POOL="replace_with_your_pool_and_port"
#ALTCOM_POOL="replace_with_your_pool_and_port"
#ALTCOM_PASSWORD="x"
#ALTCOM
# 
#----  fill in your coins and uncomment the lines concerned  ----
#AMBER
#AMBER_WORKER=$WORKERNAME
#AMBER_ADDRESS="replace_with_your_ZCL_address"
#AMBER_POOL="replace_with_your_pool_and_port"
#AMBER_POOL="replace_with_your_pool_and_port"
#AMBER_PASSWORD="x"
#AMBER
# 
#----  fill in your coins and uncomment the lines concerned  ----
#AMS
#AMS_WORKER=$WORKERNAME
#AMS_ADDRESS="replace_with_your_ZCL_address"
#AMS_POOL="replace_with_your_pool_and_port"
#AMS_POOL="replace_with_your_pool_and_port"
#AMS_PASSWORD="x"
#AMS
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ARG
#ARG_WORKER=$WORKERNAME
#ARG_ADDRESS="replace_with_your_ZCL_address"
#ARG_POOL="replace_with_your_pool_and_port"
#ARG_POOL="replace_with_your_pool_and_port"
#ARG_PASSWORD="x"
#ARG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ARG
#ARG_WORKER=$WORKERNAME
#ARG_ADDRESS="replace_with_your_ZCL_address"
#ARG_POOL="replace_with_your_pool_and_port"
#ARG_POOL="replace_with_your_pool_and_port"
#ARG_PASSWORD="x"
#ARG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ARI
#ARI_WORKER=$WORKERNAME
#ARI_ADDRESS="replace_with_your_ZCL_address"
#ARI_POOL="replace_with_your_pool_and_port"
#ARI_POOL="replace_with_your_pool_and_port"
#ARI_PASSWORD="x"
#ARI
# 
#----  fill in your coins and uncomment the lines concerned  ----
#AUR
#AUR_WORKER=$WORKERNAME
#AUR_ADDRESS="replace_with_your_ZCL_address"
#AUR_POOL="replace_with_your_pool_and_port"
#AUR_POOL="replace_with_your_pool_and_port"
#AUR_PASSWORD="x"
#AUR
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BCH
#BCH_WORKER=$WORKERNAME
#BCH_ADDRESS="replace_with_your_ZCL_address"
#BCH_POOL="replace_with_your_pool_and_port"
#BCH_POOL="replace_with_your_pool_and_port"
#BCH_PASSWORD="x"
#BCH
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BCN
#BCN_WORKER=$WORKERNAME
#BCN_ADDRESS="replace_with_your_ZCL_address"
#BCN_POOL="replace_with_your_pool_and_port"
#BCN_POOL="replace_with_your_pool_and_port"
#BCN_PASSWORD="x"
#BCN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BELA
#BELA_WORKER=$WORKERNAME
#BELA_ADDRESS="replace_with_your_ZCL_address"
#BELA_POOL="replace_with_your_pool_and_port"
#BELA_POOL="replace_with_your_pool_and_port"
#BELA_PASSWORD="x"
#BELA
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BIP
#BIP_WORKER=$WORKERNAME
#BIP_ADDRESS="replace_with_your_ZCL_address"
#BIP_POOL="replace_with_your_pool_and_port"
#BIP_POOL="replace_with_your_pool_and_port"
#BIP_PASSWORD="x"
#BIP
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BOB
#BOB_WORKER=$WORKERNAME
#BOB_ADDRESS="replace_with_your_ZCL_address"
#BOB_POOL="replace_with_your_pool_and_port"
#BOB_POOL="replace_with_your_pool_and_port"
#BOB_PASSWORD="x"
#BOB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BSD
#BSD_WORKER=$WORKERNAME
#BSD_ADDRESS="replace_with_your_ZCL_address"
#BSD_POOL="replace_with_your_pool_and_port"
#BSD_POOL="replace_with_your_pool_and_port"
#BSD_PASSWORD="x"
#BSD
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BSTY
#BSTY_WORKER=$WORKERNAME
#BSTY_ADDRESS="replace_with_your_ZCL_address"
#BSTY_POOL="replace_with_your_pool_and_port"
#BSTY_POOL="replace_with_your_pool_and_port"
#BSTY_PASSWORD="x"
#BSTY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BTA
#BTA_WORKER=$WORKERNAME
#BTA_ADDRESS="replace_with_your_ZCL_address"
#BTA_POOL="replace_with_your_pool_and_port"
#BTA_POOL="replace_with_your_pool_and_port"
#BTA_PASSWORD="x"
#BTA
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BTC
#BTC_WORKER=$WORKERNAME
#BTC_ADDRESS="replace_with_your_ZCL_address"
#BTC_POOL="replace_with_your_pool_and_port"
#BTC_POOL="replace_with_your_pool_and_port"
#BTC_PASSWORD="x"
#BTC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BTCZ
#BTCZ_WORKER=$WORKERNAME
#BTCZ_ADDRESS="replace_with_your_ZCL_address"
#BTCZ_POOL="replace_with_your_pool_and_port"
#BTCZ_POOL="replace_with_your_pool_and_port"
#BTCZ_PASSWORD="x"
#BTCZ
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BTG
#BTG_WORKER=$WORKERNAME
#BTG_ADDRESS="replace_with_your_ZCL_address"
#BTG_POOL="replace_with_your_pool_and_port"
#BTG_POOL="replace_with_your_pool_and_port"
#BTG_PASSWORD="x"
#BTG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BTM
#BTM_WORKER=$WORKERNAME
#BTM_ADDRESS="replace_with_your_ZCL_address"
#BTM_POOL="replace_with_your_pool_and_port"
#BTM_POOL="replace_with_your_pool_and_port"
#BTM_PASSWORD="x"
#BTM
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BTX
#BTX_WORKER=$WORKERNAME
#BTX_ADDRESS="replace_with_your_ZCL_address"
#BTX_POOL="replace_with_your_pool_and_port"
#BTX_POOL="replace_with_your_pool_and_port"
#BTX_PASSWORD="x"
#BTX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BURN
#BURN_WORKER=$WORKERNAME
#BURN_ADDRESS="replace_with_your_ZCL_address"
#BURN_POOL="replace_with_your_pool_and_port"
#BURN_POOL="replace_with_your_pool_and_port"
#BURN_PASSWORD="x"
#BURN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#BWK
#BWK_WORKER=$WORKERNAME
#BWK_ADDRESS="replace_with_your_ZCL_address"
#BWK_POOL="replace_with_your_pool_and_port"
#BWK_POOL="replace_with_your_pool_and_port"
#BWK_PASSWORD="x"
#BWK
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CACH
#CACH_WORKER=$WORKERNAME
#CACH_ADDRESS="replace_with_your_ZCL_address"
#CACH_POOL="replace_with_your_pool_and_port"
#CACH_POOL="replace_with_your_pool_and_port"
#CACH_PASSWORD="x"
#CACH
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CANN
#CANN_WORKER=$WORKERNAME
#CANN_ADDRESS="replace_with_your_ZCL_address"
#CANN_POOL="replace_with_your_pool_and_port"
#CANN_POOL="replace_with_your_pool_and_port"
#CANN_PASSWORD="x"
#CANN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CAP
#CAP_WORKER=$WORKERNAME
#CAP_ADDRESS="replace_with_your_ZCL_address"
#CAP_POOL="replace_with_your_pool_and_port"
#CAP_POOL="replace_with_your_pool_and_port"
#CAP_PASSWORD="x"
#CAP
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CAT
#CAT_WORKER=$WORKERNAME
#CAT_ADDRESS="replace_with_your_ZCL_address"
#CAT_POOL="replace_with_your_pool_and_port"
#CAT_POOL="replace_with_your_pool_and_port"
#CAT_PASSWORD="x"
#CAT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CBX
#CBX_WORKER=$WORKERNAME
#CBX_ADDRESS="replace_with_your_ZCL_address"
#CBX_POOL="replace_with_your_pool_and_port"
#CBX_POOL="replace_with_your_pool_and_port"
#CBX_PASSWORD="x"
#CBX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CHILD
#CHILD_WORKER=$WORKERNAME
#CHILD_ADDRESS="replace_with_your_ZCL_address"
#CHILD_POOL="replace_with_your_pool_and_port"
#CHILD_POOL="replace_with_your_pool_and_port"
#CHILD_PASSWORD="x"
#CHILD
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CKC
#CKC_WORKER=$WORKERNAME
#CKC_ADDRESS="replace_with_your_ZCL_address"
#CKC_POOL="replace_with_your_pool_and_port"
#CKC_POOL="replace_with_your_pool_and_port"
#CKC_PASSWORD="x"
#CKC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CLOAK
#CLOAK_WORKER=$WORKERNAME
#CLOAK_ADDRESS="replace_with_your_ZCL_address"
#CLOAK_POOL="replace_with_your_pool_and_port"
#CLOAK_POOL="replace_with_your_pool_and_port"
#CLOAK_PASSWORD="x"
#CLOAK
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CRC
#CRC_WORKER=$WORKERNAME
#CRC_ADDRESS="replace_with_your_ZCL_address"
#CRC_POOL="replace_with_your_pool_and_port"
#CRC_POOL="replace_with_your_pool_and_port"
#CRC_PASSWORD="x"
#CRC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CREA
#CREA_WORKER=$WORKERNAME
#CREA_ADDRESS="replace_with_your_ZCL_address"
#CREA_POOL="replace_with_your_pool_and_port"
#CREA_POOL="replace_with_your_pool_and_port"
#CREA_PASSWORD="x"
#CREA
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CRM
#CRM_WORKER=$WORKERNAME
#CRM_ADDRESS="replace_with_your_ZCL_address"
#CRM_POOL="replace_with_your_pool_and_port"
#CRM_POOL="replace_with_your_pool_and_port"
#CRM_PASSWORD="x"
#CRM
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CROC
#CROC_WORKER=$WORKERNAME
#CROC_ADDRESS="replace_with_your_ZCL_address"
#CROC_POOL="replace_with_your_pool_and_port"
#CROC_POOL="replace_with_your_pool_and_port"
#CROC_PASSWORD="x"
#CROC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CRW
#CRW_WORKER=$WORKERNAME
#CRW_ADDRESS="replace_with_your_ZCL_address"
#CRW_POOL="replace_with_your_pool_and_port"
#CRW_POOL="replace_with_your_pool_and_port"
#CRW_PASSWORD="x"
#CRW
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CRYPT
#CRYPT_WORKER=$WORKERNAME
#CRYPT_ADDRESS="replace_with_your_ZCL_address"
#CRYPT_POOL="replace_with_your_pool_and_port"
#CRYPT_POOL="replace_with_your_pool_and_port"
#CRYPT_PASSWORD="x"
#CRYPT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CTO
#CTO_WORKER=$WORKERNAME
#CTO_ADDRESS="replace_with_your_ZCL_address"
#CTO_POOL="replace_with_your_pool_and_port"
#CTO_POOL="replace_with_your_pool_and_port"
#CTO_PASSWORD="x"
#CTO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#CURE
#CURE_WORKER=$WORKERNAME
#CURE_ADDRESS="replace_with_your_ZCL_address"
#CURE_POOL="replace_with_your_pool_and_port"
#CURE_POOL="replace_with_your_pool_and_port"
#CURE_PASSWORD="x"
#CURE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DASH
#DASH_WORKER=$WORKERNAME
#DASH_ADDRESS="replace_with_your_ZCL_address"
#DASH_POOL="replace_with_your_pool_and_port"
#DASH_POOL="replace_with_your_pool_and_port"
#DASH_PASSWORD="x"
#DASH
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DCR
#DCR_WORKER=$WORKERNAME
#DCR_ADDRESS="replace_with_your_ZCL_address"
#DCR_POOL="replace_with_your_pool_and_port"
#DCR_POOL="replace_with_your_pool_and_port"
#DCR_PASSWORD="x"
#DCR
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DEM
#DEM_WORKER=$WORKERNAME
#DEM_ADDRESS="replace_with_your_ZCL_address"
#DEM_POOL="replace_with_your_pool_and_port"
#DEM_POOL="replace_with_your_pool_and_port"
#DEM_PASSWORD="x"
#DEM
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGB
#DGB_WORKER=$WORKERNAME
#DGB_ADDRESS="replace_with_your_ZCL_address"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_PASSWORD="x"
#DGB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGB
#DGB_WORKER=$WORKERNAME
#DGB_ADDRESS="replace_with_your_ZCL_address"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_PASSWORD="x"
#DGB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGB
#DGB_WORKER=$WORKERNAME
#DGB_ADDRESS="replace_with_your_ZCL_address"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_PASSWORD="x"
#DGB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGB
#DGB_WORKER=$WORKERNAME
#DGB_ADDRESS="replace_with_your_ZCL_address"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_PASSWORD="x"
#DGB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGB
#DGB_WORKER=$WORKERNAME
#DGB_ADDRESS="replace_with_your_ZCL_address"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_POOL="replace_with_your_pool_and_port"
#DGB_PASSWORD="x"
#DGB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGC
#DGC_WORKER=$WORKERNAME
#DGC_ADDRESS="replace_with_your_ZCL_address"
#DGC_POOL="replace_with_your_pool_and_port"
#DGC_POOL="replace_with_your_pool_and_port"
#DGC_PASSWORD="x"
#DGC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGC
#DGC_WORKER=$WORKERNAME
#DGC_ADDRESS="replace_with_your_ZCL_address"
#DGC_POOL="replace_with_your_pool_and_port"
#DGC_POOL="replace_with_your_pool_and_port"
#DGC_PASSWORD="x"
#DGC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DGC
#DGC_WORKER=$WORKERNAME
#DGC_ADDRESS="replace_with_your_ZCL_address"
#DGC_POOL="replace_with_your_pool_and_port"
#DGC_POOL="replace_with_your_pool_and_port"
#DGC_PASSWORD="x"
#DGC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DMD
#DMD_WORKER=$WORKERNAME
#DMD_ADDRESS="replace_with_your_ZCL_address"
#DMD_POOL="replace_with_your_pool_and_port"
#DMD_POOL="replace_with_your_pool_and_port"
#DMD_PASSWORD="x"
#DMD
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DNET
#DNET_WORKER=$WORKERNAME
#DNET_ADDRESS="replace_with_your_ZCL_address"
#DNET_POOL="replace_with_your_pool_and_port"
#DNET_POOL="replace_with_your_pool_and_port"
#DNET_PASSWORD="x"
#DNET
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DNR
#DNR_WORKER=$WORKERNAME
#DNR_ADDRESS="replace_with_your_ZCL_address"
#DNR_POOL="replace_with_your_pool_and_port"
#DNR_POOL="replace_with_your_pool_and_port"
#DNR_PASSWORD="x"
#DNR
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DOGE
#DOGE_WORKER=$WORKERNAME
#DOGE_ADDRESS="replace_with_your_ZCL_address"
#DOGE_POOL="replace_with_your_pool_and_port"
#DOGE_POOL="replace_with_your_pool_and_port"
#DOGE_PASSWORD="x"
#DOGE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DOPE
#DOPE_WORKER=$WORKERNAME
#DOPE_ADDRESS="replace_with_your_ZCL_address"
#DOPE_POOL="replace_with_your_pool_and_port"
#DOPE_POOL="replace_with_your_pool_and_port"
#DOPE_PASSWORD="x"
#DOPE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DPC
#DPC_WORKER=$WORKERNAME
#DPC_ADDRESS="replace_with_your_ZCL_address"
#DPC_POOL="replace_with_your_pool_and_port"
#DPC_POOL="replace_with_your_pool_and_port"
#DPC_PASSWORD="x"
#DPC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DSH
#DSH_WORKER=$WORKERNAME
#DSH_ADDRESS="replace_with_your_ZCL_address"
#DSH_POOL="replace_with_your_pool_and_port"
#DSH_POOL="replace_with_your_pool_and_port"
#DSH_PASSWORD="x"
#DSH
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DUO
#DUO_WORKER=$WORKERNAME
#DUO_ADDRESS="replace_with_your_ZCL_address"
#DUO_POOL="replace_with_your_pool_and_port"
#DUO_POOL="replace_with_your_pool_and_port"
#DUO_PASSWORD="x"
#DUO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#DUO
#DUO_WORKER=$WORKERNAME
#DUO_ADDRESS="replace_with_your_ZCL_address"
#DUO_POOL="replace_with_your_pool_and_port"
#DUO_POOL="replace_with_your_pool_and_port"
#DUO_PASSWORD="x"
#DUO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#EAC
#EAC_WORKER=$WORKERNAME
#EAC_ADDRESS="replace_with_your_ZCL_address"
#EAC_POOL="replace_with_your_pool_and_port"
#EAC_POOL="replace_with_your_pool_and_port"
#EAC_PASSWORD="x"
#EAC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ELLA
#ELLA_WORKER=$WORKERNAME
#ELLA_ADDRESS="replace_with_your_ZCL_address"
#ELLA_POOL="replace_with_your_pool_and_port"
#ELLA_POOL="replace_with_your_pool_and_port"
#ELLA_PASSWORD="x"
#ELLA
# 
#----  fill in your coins and uncomment the lines concerned  ----
#EMC2
#EMC2_WORKER=$WORKERNAME
#EMC2_ADDRESS="replace_with_your_ZCL_address"
#EMC2_POOL="replace_with_your_pool_and_port"
#EMC2_POOL="replace_with_your_pool_and_port"
#EMC2_PASSWORD="x"
#EMC2
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ENC
#ENC_WORKER=$WORKERNAME
#ENC_ADDRESS="replace_with_your_ZCL_address"
#ENC_POOL="replace_with_your_pool_and_port"
#ENC_POOL="replace_with_your_pool_and_port"
#ENC_PASSWORD="x"
#ENC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#EPC
#EPC_WORKER=$WORKERNAME
#EPC_ADDRESS="replace_with_your_ZCL_address"
#EPC_POOL="replace_with_your_pool_and_port"
#EPC_POOL="replace_with_your_pool_and_port"
#EPC_PASSWORD="x"
#EPC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ETC
#ETC_WORKER=$WORKERNAME
#ETC_ADDRESS="replace_with_your_ZCL_address"
#ETC_POOL="replace_with_your_pool_and_port"
#ETC_POOL="replace_with_your_pool_and_port"
#ETC_PASSWORD="x"
#ETC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ETH
#ETH_WORKER=$WORKERNAME
#ETH_ADDRESS="replace_with_your_ZCL_address"
#ETH_POOL="replace_with_your_pool_and_port"
#ETH_POOL="replace_with_your_pool_and_port"
#ETH_PASSWORD="x"
#ETH
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ETN
#ETN_WORKER=$WORKERNAME
#ETN_ADDRESS="replace_with_your_ZCL_address"
#ETN_POOL="replace_with_your_pool_and_port"
#ETN_POOL="replace_with_your_pool_and_port"
#ETN_PASSWORD="x"
#ETN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ETP
#ETP_WORKER=$WORKERNAME
#ETP_ADDRESS="replace_with_your_ZCL_address"
#ETP_POOL="replace_with_your_pool_and_port"
#ETP_POOL="replace_with_your_pool_and_port"
#ETP_PASSWORD="x"
#ETP
# 
#----  fill in your coins and uncomment the lines concerned  ----
#EXE
#EXE_WORKER=$WORKERNAME
#EXE_ADDRESS="replace_with_your_ZCL_address"
#EXE_POOL="replace_with_your_pool_and_port"
#EXE_POOL="replace_with_your_pool_and_port"
#EXE_PASSWORD="x"
#EXE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#EXP
#EXP_WORKER=$WORKERNAME
#EXP_ADDRESS="replace_with_your_ZCL_address"
#EXP_POOL="replace_with_your_pool_and_port"
#EXP_POOL="replace_with_your_pool_and_port"
#EXP_PASSWORD="x"
#EXP
# 
#----  fill in your coins and uncomment the lines concerned  ----
#FCN
#FCN_WORKER=$WORKERNAME
#FCN_ADDRESS="replace_with_your_ZCL_address"
#FCN_POOL="replace_with_your_pool_and_port"
#FCN_POOL="replace_with_your_pool_and_port"
#FCN_PASSWORD="x"
#FCN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#FLO
#FLO_WORKER=$WORKERNAME
#FLO_ADDRESS="replace_with_your_ZCL_address"
#FLO_POOL="replace_with_your_pool_and_port"
#FLO_POOL="replace_with_your_pool_and_port"
#FLO_PASSWORD="x"
#FLO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#FLT
#FLT_WORKER=$WORKERNAME
#FLT_ADDRESS="replace_with_your_ZCL_address"
#FLT_POOL="replace_with_your_pool_and_port"
#FLT_POOL="replace_with_your_pool_and_port"
#FLT_PASSWORD="x"
#FLT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#FRSH
#FRSH_WORKER=$WORKERNAME
#FRSH_ADDRESS="replace_with_your_ZCL_address"
#FRSH_POOL="replace_with_your_pool_and_port"
#FRSH_POOL="replace_with_your_pool_and_port"
#FRSH_PASSWORD="x"
#FRSH
# 
#----  fill in your coins and uncomment the lines concerned  ----
#FST
#FST_WORKER=$WORKERNAME
#FST_ADDRESS="replace_with_your_ZCL_address"
#FST_POOL="replace_with_your_pool_and_port"
#FST_POOL="replace_with_your_pool_and_port"
#FST_PASSWORD="x"
#FST
# 
#----  fill in your coins and uncomment the lines concerned  ----
#FTC
#FTC_WORKER=$WORKERNAME
#FTC_ADDRESS="replace_with_your_ZCL_address"
#FTC_POOL="replace_with_your_pool_and_port"
#FTC_POOL="replace_with_your_pool_and_port"
#FTC_PASSWORD="x"
#FTC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GAME
#GAME_WORKER=$WORKERNAME
#GAME_ADDRESS="replace_with_your_ZCL_address"
#GAME_POOL="replace_with_your_pool_and_port"
#GAME_POOL="replace_with_your_pool_and_port"
#GAME_PASSWORD="x"
#GAME
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GB
#GB_WORKER=$WORKERNAME
#GB_ADDRESS="replace_with_your_ZCL_address"
#GB_POOL="replace_with_your_pool_and_port"
#GB_POOL="replace_with_your_pool_and_port"
#GB_PASSWORD="x"
#GB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GBX
#GBX_WORKER=$WORKERNAME
#GBX_ADDRESS="replace_with_your_ZCL_address"
#GBX_POOL="replace_with_your_pool_and_port"
#GBX_POOL="replace_with_your_pool_and_port"
#GBX_PASSWORD="x"
#GBX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GDN
#GDN_WORKER=$WORKERNAME
#GDN_ADDRESS="replace_with_your_ZCL_address"
#GDN_POOL="replace_with_your_pool_and_port"
#GDN_POOL="replace_with_your_pool_and_port"
#GDN_PASSWORD="x"
#GDN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GEO
#GEO_WORKER=$WORKERNAME
#GEO_ADDRESS="replace_with_your_ZCL_address"
#GEO_POOL="replace_with_your_pool_and_port"
#GEO_POOL="replace_with_your_pool_and_port"
#GEO_PASSWORD="x"
#GEO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GLC
#GLC_WORKER=$WORKERNAME
#GLC_ADDRESS="replace_with_your_ZCL_address"
#GLC_POOL="replace_with_your_pool_and_port"
#GLC_POOL="replace_with_your_pool_and_port"
#GLC_PASSWORD="x"
#GLC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GOAL
#GOAL_WORKER=$WORKERNAME
#GOAL_ADDRESS="replace_with_your_ZCL_address"
#GOAL_POOL="replace_with_your_pool_and_port"
#GOAL_POOL="replace_with_your_pool_and_port"
#GOAL_PASSWORD="x"
#GOAL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#GRS
#GRS_WORKER=$WORKERNAME
#GRS_ADDRESS="replace_with_your_ZCL_address"
#GRS_POOL="replace_with_your_pool_and_port"
#GRS_POOL="replace_with_your_pool_and_port"
#GRS_PASSWORD="x"
#GRS
# 
#----  fill in your coins and uncomment the lines concerned  ----
#HAL
#HAL_WORKER=$WORKERNAME
#HAL_ADDRESS="replace_with_your_ZCL_address"
#HAL_POOL="replace_with_your_pool_and_port"
#HAL_POOL="replace_with_your_pool_and_port"
#HAL_PASSWORD="x"
#HAL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#HIRO
#HIRO_WORKER=$WORKERNAME
#HIRO_ADDRESS="replace_with_your_ZCL_address"
#HIRO_POOL="replace_with_your_pool_and_port"
#HIRO_POOL="replace_with_your_pool_and_port"
#HIRO_PASSWORD="x"
#HIRO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#HUSH
#HUSH_WORKER=$WORKERNAME
#HUSH_ADDRESS="replace_with_your_ZCL_address"
#HUSH_POOL="replace_with_your_pool_and_port"
#HUSH_POOL="replace_with_your_pool_and_port"
#HUSH_PASSWORD="x"
#HUSH
# 
#----  fill in your coins and uncomment the lines concerned  ----
#HVC
#HVC_WORKER=$WORKERNAME
#HVC_ADDRESS="replace_with_your_ZCL_address"
#HVC_POOL="replace_with_your_pool_and_port"
#HVC_POOL="replace_with_your_pool_and_port"
#HVC_PASSWORD="x"
#HVC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#IEC
#IEC_WORKER=$WORKERNAME
#IEC_ADDRESS="replace_with_your_ZCL_address"
#IEC_POOL="replace_with_your_pool_and_port"
#IEC_POOL="replace_with_your_pool_and_port"
#IEC_PASSWORD="x"
#IEC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#INFX
#INFX_WORKER=$WORKERNAME
#INFX_ADDRESS="replace_with_your_ZCL_address"
#INFX_POOL="replace_with_your_pool_and_port"
#INFX_POOL="replace_with_your_pool_and_port"
#INFX_PASSWORD="x"
#INFX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#JPC
#JPC_WORKER=$WORKERNAME
#JPC_ADDRESS="replace_with_your_ZCL_address"
#JPC_POOL="replace_with_your_pool_and_port"
#JPC_POOL="replace_with_your_pool_and_port"
#JPC_PASSWORD="x"
#JPC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#KARM
#KARM_WORKER=$WORKERNAME
#KARM_ADDRESS="replace_with_your_ZCL_address"
#KARM_POOL="replace_with_your_pool_and_port"
#KARM_POOL="replace_with_your_pool_and_port"
#KARM_PASSWORD="x"
#KARM
# 
#----  fill in your coins and uncomment the lines concerned  ----
#KMD
#KMD_WORKER=$WORKERNAME
#KMD_ADDRESS="replace_with_your_ZCL_address"
#KMD_POOL="replace_with_your_pool_and_port"
#KMD_POOL="replace_with_your_pool_and_port"
#KMD_PASSWORD="x"
#KMD
# 
#----  fill in your coins and uncomment the lines concerned  ----
#KR
#KR_WORKER=$WORKERNAME
#KR_ADDRESS="replace_with_your_ZCL_address"
#KR_POOL="replace_with_your_pool_and_port"
#KR_POOL="replace_with_your_pool_and_port"
#KR_PASSWORD="x"
#KR
# 
#----  fill in your coins and uncomment the lines concerned  ----
#KRB
#KRB_WORKER=$WORKERNAME
#KRB_ADDRESS="replace_with_your_ZCL_address"
#KRB_POOL="replace_with_your_pool_and_port"
#KRB_POOL="replace_with_your_pool_and_port"
#KRB_PASSWORD="x"
#KRB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LBC
#LBC_WORKER=$WORKERNAME
#LBC_ADDRESS="replace_with_your_ZCL_address"
#LBC_POOL="replace_with_your_pool_and_port"
#LBC_POOL="replace_with_your_pool_and_port"
#LBC_PASSWORD="x"
#LBC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LGC
#LGC_WORKER=$WORKERNAME
#LGC_ADDRESS="replace_with_your_ZCL_address"
#LGC_POOL="replace_with_your_pool_and_port"
#LGC_POOL="replace_with_your_pool_and_port"
#LGC_PASSWORD="x"
#LGC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LGD
#LGD_WORKER=$WORKERNAME
#LGD_ADDRESS="replace_with_your_ZCL_address"
#LGD_POOL="replace_with_your_pool_and_port"
#LGD_POOL="replace_with_your_pool_and_port"
#LGD_PASSWORD="x"
#LGD
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LIMX
#LIMX_WORKER=$WORKERNAME
#LIMX_ADDRESS="replace_with_your_ZCL_address"
#LIMX_POOL="replace_with_your_pool_and_port"
#LIMX_POOL="replace_with_your_pool_and_port"
#LIMX_PASSWORD="x"
#LIMX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LINX
#LINX_WORKER=$WORKERNAME
#LINX_ADDRESS="replace_with_your_ZCL_address"
#LINX_POOL="replace_with_your_pool_and_port"
#LINX_POOL="replace_with_your_pool_and_port"
#LINX_PASSWORD="x"
#LINX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LTC
#LTC_WORKER=$WORKERNAME
#LTC_ADDRESS="replace_with_your_ZCL_address"
#LTC_POOL="replace_with_your_pool_and_port"
#LTC_POOL="replace_with_your_pool_and_port"
#LTC_PASSWORD="x"
#LTC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LTCX
#LTCX_WORKER=$WORKERNAME
#LTCX_ADDRESS="replace_with_your_ZCL_address"
#LTCX_POOL="replace_with_your_pool_and_port"
#LTCX_POOL="replace_with_your_pool_and_port"
#LTCX_PASSWORD="x"
#LTCX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#LUX
#LUX_WORKER=$WORKERNAME
#LUX_ADDRESS="replace_with_your_ZCL_address"
#LUX_POOL="replace_with_your_pool_and_port"
#LUX_POOL="replace_with_your_pool_and_port"
#LUX_PASSWORD="x"
#LUX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MARU
#MARU_WORKER=$WORKERNAME
#MARU_ADDRESS="replace_with_your_ZCL_address"
#MARU_POOL="replace_with_your_pool_and_port"
#MARU_POOL="replace_with_your_pool_and_port"
#MARU_PASSWORD="x"
#MARU
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MAX
#MAX_WORKER=$WORKERNAME
#MAX_ADDRESS="replace_with_your_ZCL_address"
#MAX_POOL="replace_with_your_pool_and_port"
#MAX_POOL="replace_with_your_pool_and_port"
#MAX_PASSWORD="x"
#MAX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MEC
#MEC_WORKER=$WORKERNAME
#MEC_ADDRESS="replace_with_your_ZCL_address"
#MEC_POOL="replace_with_your_pool_and_port"
#MEC_POOL="replace_with_your_pool_and_port"
#MEC_PASSWORD="x"
#MEC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MEOW
#MEOW_WORKER=$WORKERNAME
#MEOW_ADDRESS="replace_with_your_ZCL_address"
#MEOW_POOL="replace_with_your_pool_and_port"
#MEOW_POOL="replace_with_your_pool_and_port"
#MEOW_PASSWORD="x"
#MEOW
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MIL
#MIL_WORKER=$WORKERNAME
#MIL_ADDRESS="replace_with_your_ZCL_address"
#MIL_POOL="replace_with_your_pool_and_port"
#MIL_POOL="replace_with_your_pool_and_port"
#MIL_PASSWORD="x"
#MIL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MND
#MND_WORKER=$WORKERNAME
#MND_ADDRESS="replace_with_your_ZCL_address"
#MND_POOL="replace_with_your_pool_and_port"
#MND_POOL="replace_with_your_pool_and_port"
#MND_PASSWORD="x"
#MND
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MONA
#MONA_WORKER=$WORKERNAME
#MONA_ADDRESS="replace_with_your_ZCL_address"
#MONA_POOL="replace_with_your_pool_and_port"
#MONA_POOL="replace_with_your_pool_and_port"
#MONA_PASSWORD="x"
#MONA
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MOON
#MOON_WORKER=$WORKERNAME
#MOON_ADDRESS="replace_with_your_ZCL_address"
#MOON_POOL="replace_with_your_pool_and_port"
#MOON_POOL="replace_with_your_pool_and_port"
#MOON_PASSWORD="x"
#MOON
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MRC
#MRC_WORKER=$WORKERNAME
#MRC_ADDRESS="replace_with_your_ZCL_address"
#MRC_POOL="replace_with_your_pool_and_port"
#MRC_POOL="replace_with_your_pool_and_port"
#MRC_PASSWORD="x"
#MRC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MUE
#MUE_WORKER=$WORKERNAME
#MUE_ADDRESS="replace_with_your_ZCL_address"
#MUE_POOL="replace_with_your_pool_and_port"
#MUE_POOL="replace_with_your_pool_and_port"
#MUE_PASSWORD="x"
#MUE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MUN
#MUN_WORKER=$WORKERNAME
#MUN_ADDRESS="replace_with_your_ZCL_address"
#MUN_POOL="replace_with_your_pool_and_port"
#MUN_POOL="replace_with_your_pool_and_port"
#MUN_PASSWORD="x"
#MUN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MUSIC
#MUSIC_WORKER=$WORKERNAME
#MUSIC_ADDRESS="replace_with_your_ZCL_address"
#MUSIC_POOL="replace_with_your_pool_and_port"
#MUSIC_POOL="replace_with_your_pool_and_port"
#MUSIC_PASSWORD="x"
#MUSIC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#MZC
#MZC_WORKER=$WORKERNAME
#MZC_ADDRESS="replace_with_your_ZCL_address"
#MZC_POOL="replace_with_your_pool_and_port"
#MZC_POOL="replace_with_your_pool_and_port"
#MZC_PASSWORD="x"
#MZC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#NAUT
#NAUT_WORKER=$WORKERNAME
#NAUT_ADDRESS="replace_with_your_ZCL_address"
#NAUT_POOL="replace_with_your_pool_and_port"
#NAUT_POOL="replace_with_your_pool_and_port"
#NAUT_PASSWORD="x"
#NAUT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#NLG
#NLG_WORKER=$WORKERNAME
#NLG_ADDRESS="replace_with_your_ZCL_address"
#NLG_POOL="replace_with_your_pool_and_port"
#NLG_POOL="replace_with_your_pool_and_port"
#NLG_PASSWORD="x"
#NLG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#NMC
#NMC_WORKER=$WORKERNAME
#NMC_ADDRESS="replace_with_your_ZCL_address"
#NMC_POOL="replace_with_your_pool_and_port"
#NMC_POOL="replace_with_your_pool_and_port"
#NMC_PASSWORD="x"
#NMC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#NOBL
#NOBL_WORKER=$WORKERNAME
#NOBL_ADDRESS="replace_with_your_ZCL_address"
#NOBL_POOL="replace_with_your_pool_and_port"
#NOBL_POOL="replace_with_your_pool_and_port"
#NOBL_PASSWORD="x"
#NOBL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#NOTE
#NOTE_WORKER=$WORKERNAME
#NOTE_ADDRESS="replace_with_your_ZCL_address"
#NOTE_POOL="replace_with_your_pool_and_port"
#NOTE_POOL="replace_with_your_pool_and_port"
#NOTE_PASSWORD="x"
#NOTE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#NVC
#NVC_WORKER=$WORKERNAME
#NVC_ADDRESS="replace_with_your_ZCL_address"
#NVC_POOL="replace_with_your_pool_and_port"
#NVC_POOL="replace_with_your_pool_and_port"
#NVC_PASSWORD="x"
#NVC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#NYAN
#NYAN_WORKER=$WORKERNAME
#NYAN_ADDRESS="replace_with_your_ZCL_address"
#NYAN_POOL="replace_with_your_pool_and_port"
#NYAN_POOL="replace_with_your_pool_and_port"
#NYAN_PASSWORD="x"
#NYAN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ONION
#ONION_WORKER=$WORKERNAME
#ONION_ADDRESS="replace_with_your_ZCL_address"
#ONION_POOL="replace_with_your_pool_and_port"
#ONION_POOL="replace_with_your_pool_and_port"
#ONION_PASSWORD="x"
#ONION
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ONX
#ONX_WORKER=$WORKERNAME
#ONX_ADDRESS="replace_with_your_ZCL_address"
#ONX_POOL="replace_with_your_pool_and_port"
#ONX_POOL="replace_with_your_pool_and_port"
#ONX_PASSWORD="x"
#ONX
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ORB
#ORB_WORKER=$WORKERNAME
#ORB_ADDRESS="replace_with_your_ZCL_address"
#ORB_POOL="replace_with_your_pool_and_port"
#ORB_POOL="replace_with_your_pool_and_port"
#ORB_PASSWORD="x"
#ORB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#PASC
#PASC_WORKER=$WORKERNAME
#PASC_ADDRESS="replace_with_your_ZCL_address"
#PASC_POOL="replace_with_your_pool_and_port"
#PASC_POOL="replace_with_your_pool_and_port"
#PASC_PASSWORD="x"
#PASC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#PASL
#PASL_WORKER=$WORKERNAME
#PASL_ADDRESS="replace_with_your_ZCL_address"
#PASL_POOL="replace_with_your_pool_and_port"
#PASL_POOL="replace_with_your_pool_and_port"
#PASL_PASSWORD="x"
#PASL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#PINK
#PINK_WORKER=$WORKERNAME
#PINK_ADDRESS="replace_with_your_ZCL_address"
#PINK_POOL="replace_with_your_pool_and_port"
#PINK_POOL="replace_with_your_pool_and_port"
#PINK_PASSWORD="x"
#PINK
# 
#----  fill in your coins and uncomment the lines concerned  ----
#PIRL
#PIRL_WORKER=$WORKERNAME
#PIRL_ADDRESS="replace_with_your_ZCL_address"
#PIRL_POOL="replace_with_your_pool_and_port"
#PIRL_POOL="replace_with_your_pool_and_port"
#PIRL_PASSWORD="x"
#PIRL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#POT
#POT_WORKER=$WORKERNAME
#POT_ADDRESS="replace_with_your_ZCL_address"
#POT_POOL="replace_with_your_pool_and_port"
#POT_POOL="replace_with_your_pool_and_port"
#POT_PASSWORD="x"
#POT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#PPC
#PPC_WORKER=$WORKERNAME
#PPC_ADDRESS="replace_with_your_ZCL_address"
#PPC_POOL="replace_with_your_pool_and_port"
#PPC_POOL="replace_with_your_pool_and_port"
#PPC_PASSWORD="x"
#PPC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#PXC
#PXC_WORKER=$WORKERNAME
#PXC_ADDRESS="replace_with_your_ZCL_address"
#PXC_POOL="replace_with_your_pool_and_port"
#PXC_POOL="replace_with_your_pool_and_port"
#PXC_PASSWORD="x"
#PXC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#PXI
#PXI_WORKER=$WORKERNAME
#PXI_ADDRESS="replace_with_your_ZCL_address"
#PXI_POOL="replace_with_your_pool_and_port"
#PXI_POOL="replace_with_your_pool_and_port"
#PXI_PASSWORD="x"
#PXI
# 
#----  fill in your coins and uncomment the lines concerned  ----
#QBC
#QBC_WORKER=$WORKERNAME
#QBC_ADDRESS="replace_with_your_ZCL_address"
#QBC_POOL="replace_with_your_pool_and_port"
#QBC_POOL="replace_with_your_pool_and_port"
#QBC_PASSWORD="x"
#QBC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#QCN
#QCN_WORKER=$WORKERNAME
#QCN_ADDRESS="replace_with_your_ZCL_address"
#QCN_POOL="replace_with_your_pool_and_port"
#QCN_POOL="replace_with_your_pool_and_port"
#QCN_PASSWORD="x"
#QCN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#QRK
#QRK_WORKER=$WORKERNAME
#QRK_ADDRESS="replace_with_your_ZCL_address"
#QRK_POOL="replace_with_your_pool_and_port"
#QRK_POOL="replace_with_your_pool_and_port"
#QRK_PASSWORD="x"
#QRK
# 
#----  fill in your coins and uncomment the lines concerned  ----
#RBY
#RBY_WORKER=$WORKERNAME
#RBY_ADDRESS="replace_with_your_ZCL_address"
#RBY_POOL="replace_with_your_pool_and_port"
#RBY_POOL="replace_with_your_pool_and_port"
#RBY_PASSWORD="x"
#RBY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#RDD
#RDD_WORKER=$WORKERNAME
#RDD_ADDRESS="replace_with_your_ZCL_address"
#RDD_POOL="replace_with_your_pool_and_port"
#RDD_POOL="replace_with_your_pool_and_port"
#RDD_PASSWORD="x"
#RDD
# 
#----  fill in your coins and uncomment the lines concerned  ----
#RIPO
#RIPO_WORKER=$WORKERNAME
#RIPO_ADDRESS="replace_with_your_ZCL_address"
#RIPO_POOL="replace_with_your_pool_and_port"
#RIPO_POOL="replace_with_your_pool_and_port"
#RIPO_PASSWORD="x"
#RIPO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#RPC
#RPC_WORKER=$WORKERNAME
#RPC_ADDRESS="replace_with_your_ZCL_address"
#RPC_POOL="replace_with_your_pool_and_port"
#RPC_POOL="replace_with_your_pool_and_port"
#RPC_PASSWORD="x"
#RPC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#RZR
#RZR_WORKER=$WORKERNAME
#RZR_ADDRESS="replace_with_your_ZCL_address"
#RZR_POOL="replace_with_your_pool_and_port"
#RZR_POOL="replace_with_your_pool_and_port"
#RZR_PASSWORD="x"
#RZR
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SAT2
#SAT2_WORKER=$WORKERNAME
#SAT2_ADDRESS="replace_with_your_ZCL_address"
#SAT2_POOL="replace_with_your_pool_and_port"
#SAT2_POOL="replace_with_your_pool_and_port"
#SAT2_PASSWORD="x"
#SAT2
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SC
#SC_WORKER=$WORKERNAME
#SC_ADDRESS="replace_with_your_ZCL_address"
#SC_POOL="replace_with_your_pool_and_port"
#SC_POOL="replace_with_your_pool_and_port"
#SC_PASSWORD="x"
#SC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SCORE
#SCORE_WORKER=$WORKERNAME
#SCORE_ADDRESS="replace_with_your_ZCL_address"
#SCORE_POOL="replace_with_your_pool_and_port"
#SCORE_POOL="replace_with_your_pool_and_port"
#SCORE_PASSWORD="x"
#SCORE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SHIFT
#SHIFT_WORKER=$WORKERNAME
#SHIFT_ADDRESS="replace_with_your_ZCL_address"
#SHIFT_POOL="replace_with_your_pool_and_port"
#SHIFT_POOL="replace_with_your_pool_and_port"
#SHIFT_PASSWORD="x"
#SHIFT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SIB
#SIB_WORKER=$WORKERNAME
#SIB_ADDRESS="replace_with_your_ZCL_address"
#SIB_POOL="replace_with_your_pool_and_port"
#SIB_POOL="replace_with_your_pool_and_port"
#SIB_PASSWORD="x"
#SIB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SIGT
#SIGT_WORKER=$WORKERNAME
#SIGT_ADDRESS="replace_with_your_ZCL_address"
#SIGT_POOL="replace_with_your_pool_and_port"
#SIGT_POOL="replace_with_your_pool_and_port"
#SIGT_PASSWORD="x"
#SIGT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SLG
#SLG_WORKER=$WORKERNAME
#SLG_ADDRESS="replace_with_your_ZCL_address"
#SLG_POOL="replace_with_your_pool_and_port"
#SLG_POOL="replace_with_your_pool_and_port"
#SLG_PASSWORD="x"
#SLG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SMART
#SMART_WORKER=$WORKERNAME
#SMART_ADDRESS="replace_with_your_ZCL_address"
#SMART_POOL="replace_with_your_pool_and_port"
#SMART_POOL="replace_with_your_pool_and_port"
#SMART_PASSWORD="x"
#SMART
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SMC
#SMC_WORKER=$WORKERNAME
#SMC_ADDRESS="replace_with_your_ZCL_address"
#SMC_POOL="replace_with_your_pool_and_port"
#SMC_POOL="replace_with_your_pool_and_port"
#SMC_PASSWORD="x"
#SMC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SOIL
#SOIL_WORKER=$WORKERNAME
#SOIL_ADDRESS="replace_with_your_ZCL_address"
#SOIL_POOL="replace_with_your_pool_and_port"
#SOIL_POOL="replace_with_your_pool_and_port"
#SOIL_PASSWORD="x"
#SOIL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SPA
#SPA_WORKER=$WORKERNAME
#SPA_ADDRESS="replace_with_your_ZCL_address"
#SPA_POOL="replace_with_your_pool_and_port"
#SPA_POOL="replace_with_your_pool_and_port"
#SPA_PASSWORD="x"
#SPA
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SPC
#SPC_WORKER=$WORKERNAME
#SPC_ADDRESS="replace_with_your_ZCL_address"
#SPC_POOL="replace_with_your_pool_and_port"
#SPC_POOL="replace_with_your_pool_and_port"
#SPC_PASSWORD="x"
#SPC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SRC
#SRC_WORKER=$WORKERNAME
#SRC_ADDRESS="replace_with_your_ZCL_address"
#SRC_POOL="replace_with_your_pool_and_port"
#SRC_POOL="replace_with_your_pool_and_port"
#SRC_PASSWORD="x"
#SRC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#START
#START_WORKER=$WORKERNAME
#START_ADDRESS="replace_with_your_ZCL_address"
#START_POOL="replace_with_your_pool_and_port"
#START_POOL="replace_with_your_pool_and_port"
#START_PASSWORD="x"
#START
# 
#----  fill in your coins and uncomment the lines concerned  ----
#SUMO
#SUMO_WORKER=$WORKERNAME
#SUMO_ADDRESS="replace_with_your_ZCL_address"
#SUMO_POOL="replace_with_your_pool_and_port"
#SUMO_POOL="replace_with_your_pool_and_port"
#SUMO_PASSWORD="x"
#SUMO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#TAC
#TAC_WORKER=$WORKERNAME
#TAC_ADDRESS="replace_with_your_ZCL_address"
#TAC_POOL="replace_with_your_pool_and_port"
#TAC_POOL="replace_with_your_pool_and_port"
#TAC_PASSWORD="x"
#TAC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#TIPS
#TIPS_WORKER=$WORKERNAME
#TIPS_ADDRESS="replace_with_your_ZCL_address"
#TIPS_POOL="replace_with_your_pool_and_port"
#TIPS_POOL="replace_with_your_pool_and_port"
#TIPS_PASSWORD="x"
#TIPS
# 
#----  fill in your coins and uncomment the lines concerned  ----
#TZC
#TZC_WORKER=$WORKERNAME
#TZC_ADDRESS="replace_with_your_ZCL_address"
#TZC_POOL="replace_with_your_pool_and_port"
#TZC_POOL="replace_with_your_pool_and_port"
#TZC_PASSWORD="x"
#TZC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#UBQ
#UBQ_WORKER=$WORKERNAME
#UBQ_ADDRESS="replace_with_your_ZCL_address"
#UBQ_POOL="replace_with_your_pool_and_port"
#UBQ_POOL="replace_with_your_pool_and_port"
#UBQ_PASSWORD="x"
#UBQ
# 
#----  fill in your coins and uncomment the lines concerned  ----
#UNB
#UNB_WORKER=$WORKERNAME
#UNB_ADDRESS="replace_with_your_ZCL_address"
#UNB_POOL="replace_with_your_pool_and_port"
#UNB_POOL="replace_with_your_pool_and_port"
#UNB_PASSWORD="x"
#UNB
# 
#----  fill in your coins and uncomment the lines concerned  ----
#UNIT
#UNIT_WORKER=$WORKERNAME
#UNIT_ADDRESS="replace_with_your_ZCL_address"
#UNIT_POOL="replace_with_your_pool_and_port"
#UNIT_POOL="replace_with_your_pool_and_port"
#UNIT_PASSWORD="x"
#UNIT
# 
#----  fill in your coins and uncomment the lines concerned  ----
#UNO
#UNO_WORKER=$WORKERNAME
#UNO_ADDRESS="replace_with_your_ZCL_address"
#UNO_POOL="replace_with_your_pool_and_port"
#UNO_POOL="replace_with_your_pool_and_port"
#UNO_PASSWORD="x"
#UNO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#UPM
#UPM_WORKER=$WORKERNAME
#UPM_ADDRESS="replace_with_your_ZCL_address"
#UPM_POOL="replace_with_your_pool_and_port"
#UPM_POOL="replace_with_your_pool_and_port"
#UPM_PASSWORD="x"
#UPM
# 
#----  fill in your coins and uncomment the lines concerned  ----
#URO
#URO_WORKER=$WORKERNAME
#URO_ADDRESS="replace_with_your_ZCL_address"
#URO_POOL="replace_with_your_pool_and_port"
#URO_POOL="replace_with_your_pool_and_port"
#URO_PASSWORD="x"
#URO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#USDE
#USDE_WORKER=$WORKERNAME
#USDE_ADDRESS="replace_with_your_ZCL_address"
#USDE_POOL="replace_with_your_pool_and_port"
#USDE_POOL="replace_with_your_pool_and_port"
#USDE_PASSWORD="x"
#USDE
# 
#----  fill in your coins and uncomment the lines concerned  ----
#UTC
#UTC_WORKER=$WORKERNAME
#UTC_ADDRESS="replace_with_your_ZCL_address"
#UTC_POOL="replace_with_your_pool_and_port"
#UTC_POOL="replace_with_your_pool_and_port"
#UTC_PASSWORD="x"
#UTC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#VEIL
#VEIL_WORKER=$WORKERNAME
#VEIL_ADDRESS="replace_with_your_ZCL_address"
#VEIL_POOL="replace_with_your_pool_and_port"
#VEIL_POOL="replace_with_your_pool_and_port"
#VEIL_PASSWORD="x"
#VEIL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#VIA
#VIA_WORKER=$WORKERNAME
#VIA_ADDRESS="replace_with_your_ZCL_address"
#VIA_POOL="replace_with_your_pool_and_port"
#VIA_POOL="replace_with_your_pool_and_port"
#VIA_PASSWORD="x"
#VIA
# 
#----  fill in your coins and uncomment the lines concerned  ----
#VIVO
#VIVO_WORKER=$WORKERNAME
#VIVO_ADDRESS="replace_with_your_ZCL_address"
#VIVO_POOL="replace_with_your_pool_and_port"
#VIVO_POOL="replace_with_your_pool_and_port"
#VIVO_PASSWORD="x"
#VIVO
# 
#----  fill in your coins and uncomment the lines concerned  ----
#VMC
#VMC_WORKER=$WORKERNAME
#VMC_ADDRESS="replace_with_your_ZCL_address"
#VMC_POOL="replace_with_your_pool_and_port"
#VMC_POOL="replace_with_your_pool_and_port"
#VMC_PASSWORD="x"
#VMC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#VTC
#VTC_WORKER=$WORKERNAME
#VTC_ADDRESS="replace_with_your_ZCL_address"
#VTC_POOL="replace_with_your_pool_and_port"
#VTC_POOL="replace_with_your_pool_and_port"
#VTC_PASSWORD="x"
#VTC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#WDC
#WDC_WORKER=$WORKERNAME
#WDC_ADDRESS="replace_with_your_ZCL_address"
#WDC_POOL="replace_with_your_pool_and_port"
#WDC_POOL="replace_with_your_pool_and_port"
#WDC_PASSWORD="x"
#WDC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XC
#XC_WORKER=$WORKERNAME
#XC_ADDRESS="replace_with_your_ZCL_address"
#XC_POOL="replace_with_your_pool_and_port"
#XC_POOL="replace_with_your_pool_and_port"
#XC_PASSWORD="x"
#XC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XCN
#XCN_WORKER=$WORKERNAME
#XCN_ADDRESS="replace_with_your_ZCL_address"
#XCN_POOL="replace_with_your_pool_and_port"
#XCN_POOL="replace_with_your_pool_and_port"
#XCN_PASSWORD="x"
#XCN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XDN
#XDN_WORKER=$WORKERNAME
#XDN_ADDRESS="replace_with_your_ZCL_address"
#XDN_POOL="replace_with_your_pool_and_port"
#XDN_POOL="replace_with_your_pool_and_port"
#XDN_PASSWORD="x"
#XDN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XHC
#XHC_WORKER=$WORKERNAME
#XHC_ADDRESS="replace_with_your_ZCL_address"
#XHC_POOL="replace_with_your_pool_and_port"
#XHC_POOL="replace_with_your_pool_and_port"
#XHC_PASSWORD="x"
#XHC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XLR
#XLR_WORKER=$WORKERNAME
#XLR_ADDRESS="replace_with_your_ZCL_address"
#XLR_POOL="replace_with_your_pool_and_port"
#XLR_POOL="replace_with_your_pool_and_port"
#XLR_PASSWORD="x"
#XLR
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XMCC
#XMCC_WORKER=$WORKERNAME
#XMCC_ADDRESS="replace_with_your_ZCL_address"
#XMCC_POOL="replace_with_your_pool_and_port"
#XMCC_POOL="replace_with_your_pool_and_port"
#XMCC_PASSWORD="x"
#XMCC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XMR
#XMR_WORKER=$WORKERNAME
#XMR_ADDRESS="replace_with_your_ZCL_address"
#XMR_POOL="replace_with_your_pool_and_port"
#XMR_POOL="replace_with_your_pool_and_port"
#XMR_PASSWORD="x"
#XMR
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XMY
#XMY_WORKER=$WORKERNAME
#XMY_ADDRESS="replace_with_your_ZCL_address"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_PASSWORD="x"
#XMY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XMY
#XMY_WORKER=$WORKERNAME
#XMY_ADDRESS="replace_with_your_ZCL_address"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_PASSWORD="x"
#XMY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XMY
#XMY_WORKER=$WORKERNAME
#XMY_ADDRESS="replace_with_your_ZCL_address"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_PASSWORD="x"
#XMY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XMY
#XMY_WORKER=$WORKERNAME
#XMY_ADDRESS="replace_with_your_ZCL_address"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_PASSWORD="x"
#XMY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XMY
#XMY_WORKER=$WORKERNAME
#XMY_ADDRESS="replace_with_your_ZCL_address"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_POOL="replace_with_your_pool_and_port"
#XMY_PASSWORD="x"
#XMY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XPY
#XPY_WORKER=$WORKERNAME
#XPY_ADDRESS="replace_with_your_ZCL_address"
#XPY_POOL="replace_with_your_pool_and_port"
#XPY_POOL="replace_with_your_pool_and_port"
#XPY_PASSWORD="x"
#XPY
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XVC
#XVC_WORKER=$WORKERNAME
#XVC_ADDRESS="replace_with_your_ZCL_address"
#XVC_POOL="replace_with_your_pool_and_port"
#XVC_POOL="replace_with_your_pool_and_port"
#XVC_PASSWORD="x"
#XVC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XVG
#XVG_WORKER=$WORKERNAME
#XVG_ADDRESS="replace_with_your_ZCL_address"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_PASSWORD="x"
#XVG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XVG
#XVG_WORKER=$WORKERNAME
#XVG_ADDRESS="replace_with_your_ZCL_address"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_PASSWORD="x"
#XVG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XVG
#XVG_WORKER=$WORKERNAME
#XVG_ADDRESS="replace_with_your_ZCL_address"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_PASSWORD="x"
#XVG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XVG
#XVG_WORKER=$WORKERNAME
#XVG_ADDRESS="replace_with_your_ZCL_address"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_PASSWORD="x"
#XVG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XVG
#XVG_WORKER=$WORKERNAME
#XVG_ADDRESS="replace_with_your_ZCL_address"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_POOL="replace_with_your_pool_and_port"
#XVG_PASSWORD="x"
#XVG
# 
#----  fill in your coins and uncomment the lines concerned  ----
#XZC
#XZC_WORKER=$WORKERNAME
#XZC_ADDRESS="replace_with_your_ZCL_address"
#XZC_POOL="replace_with_your_pool_and_port"
#XZC_POOL="replace_with_your_pool_and_port"
#XZC_PASSWORD="x"
#XZC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#YAC
#YAC_WORKER=$WORKERNAME
#YAC_ADDRESS="replace_with_your_ZCL_address"
#YAC_POOL="replace_with_your_pool_and_port"
#YAC_POOL="replace_with_your_pool_and_port"
#YAC_PASSWORD="x"
#YAC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ZCL
#ZCL_WORKER=$WORKERNAME
#ZCL_ADDRESS="replace_with_your_ZCL_address"
#ZCL_POOL="replace_with_your_pool_and_port"
#ZCL_POOL="replace_with_your_pool_and_port"
#ZCL_PASSWORD="x"
#ZCL
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ZEC
#ZEC_WORKER=$WORKERNAME
#ZEC_ADDRESS="replace_with_your_ZCL_address"
#ZEC_POOL="replace_with_your_pool_and_port"
#ZEC_POOL="replace_with_your_pool_and_port"
#ZEC_PASSWORD="x"
#ZEC
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ZEN
#ZEN_WORKER=$WORKERNAME
#ZEN_ADDRESS="replace_with_your_ZCL_address"
#ZEN_POOL="replace_with_your_pool_and_port"
#ZEN_POOL="replace_with_your_pool_and_port"
#ZEN_PASSWORD="x"
#ZEN
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ZER
#ZER_WORKER=$WORKERNAME
#ZER_ADDRESS="replace_with_your_ZCL_address"
#ZER_POOL="replace_with_your_pool_and_port"
#ZER_POOL="replace_with_your_pool_and_port"
#ZER_PASSWORD="x"
#ZER
# 
#----  fill in your coins and uncomment the lines concerned  ----
#ZET
#ZET_WORKER=$WORKERNAME
#ZET_ADDRESS="replace_with_your_ZCL_address"
#ZET_POOL="replace_with_your_pool_and_port"
#ZET_POOL="replace_with_your_pool_and_port"
#ZET_PASSWORD="x"
#ZET
# 
