#!/bin/bash
bash_new="$HOME/1bash_latest"
bash_old="$HOME/1bash"
oc_new="$HOME/1oc_latest"
oc_old="$HOME/1oc"

chmod +777 $HOME/1bash_latest
chmod +777 $HOME/1bash
chmod +777 $HOME/1oc_latest
chmod +777 $HOME/1oc

cat $bash_new | while IFS= read -r newline; do
  if [ `expr "$newline" : ".*[=].*"` -gt 0 ]; then
    echo "We found a variable : ( " $newline " )"
    cat $bash_old | while IFS= read -r oldline; do
    
      if [[ $newline == $oldline ]]; then
        echo "Same value, won't be copied over"
        continue 2
      fi

      oldline_var=${oldline%=*}
      newline_var=${newline%=*}

      if [[ $oldline_var = $newline_var ]]; then
        sed -i "s|${newline}|${oldline}|g" ${bash_new}
        echo "Remplace!"
        continue 2
      fi
    done
  fi
done
 

cat $oc_new | while IFS= read -r newline; do
  if [ `expr "$newline" : ".*[=].*"` -gt 0 ]; then
    echo "We found a variable : ( " $newline " )"
    cat $oc_old | while IFS= read -r oldline; do
    
      if [[ $newline == $oldline ]]; then
        echo "Same value, won't be copied over"
        continue 2
      fi

      oldline_var=${oldline%=*}
      newline_var=${newline%=*}

      if [[ $oldline_var = $newline_var ]]; then
        sed -i "s|${newline}|${oldline}|g" ${oc_new}
        echo "Remplace!"
        continue 2
      fi
    done
  fi
done




